apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opsler-operator
  template:
    metadata:
      labels:
        name: opsler-operator
    spec:
      containers:
        - name: opsler-operator
          image: opsler
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - opsler-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "opsler-operator"
